# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'

set -g default-shell /usr/bin/zsh
set -g default-command /usr/bin/zsh

# --- Theme: Sonokai (rounded status style) ---
set -g status-style bg='default'
set -g message-style "bg=#2c2e34,fg=#E6B450"
set -g pane-border-style "fg=#3e4451"
set -g pane-active-border-style "fg=#E6B450"

# Window list (no asterisk, clean highlight)
set-option -g window-status-format '#[fg=#5c6370,bold]#W#[default]'
set-option -g window-status-current-format '#[fg=#CAAF5F,bold]#W#[default]'
# Active window
set -g window-status-current-format '#[fg=#FF5555,bold]#I:#W#[default]'

# Inactive windows
set -g window-status-format '#[fg=#5c6370]#I:#W#[default]'


# Status bar layout and padding
set -g set-titles on
set -g status-interval 1          # refresh every 5s

set -g status-position bottom
set -g status-justify left
set -g status-left-length 100
set -g status-right-length 500

set -g status-left '#[fg=#FFAF5F,bold] #S #[fg=#5c6370,bold]|#[default] '

set -g status-right '#[fg=#FFFFFF,bold]#(~/.config/tmux/git-prompt.sh)'

# --- Keybindings ---
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 

bind-key x kill-pane
bind-key q kill-window
bind-key k kill-session 
bind m command-prompt "rename-session %%"
set-option -g detach-on-destroy off

bind-key u new-session
bind-key w new-window
bind-key -n C-S-M-h switch-client -p
bind-key -n C-S-M-l switch-client -n
bind n command-prompt -I "#W" "rename-window '%%'"

bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R


# Open fzf-tmux sessions in a popup
# Bigger popup, more usable
bind -n M-T display-popup -w 100% -h 100% -E "zsh -ic fzf-tmux-session"
bind -n M-F display-popup -w 40% -h 20% -E "zsh -ic fzf-tmux-switch"
bind -n M-G display-popup -w 100% -h 100% -E "zsh -ic fzf-tmux-gitrepo"

bind v split-window -h
bind o split-window -v

# Required for vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(n?vim|vimdiff)'"

bind -n C-h if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind -n C-j if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind -n C-k if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind -n C-l if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

# Resize panes with prefix + arrow keys
bind -r Left  resize-pane -L 5
bind -r Right resize-pane -R 5

set-option -g mouse on

unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

bind -n M-h previous-window
bind -n M-l next-window
# Previous / Next session
bind -n M-H switch-client -p
bind -n M-L switch-client -n
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloading Tmux"
run '~/.config/tmux/plugins/tpm/tpm'
