gui:
  nerdFontsVersion: "3"
  showFileIcons: true
  showFileTree: true
  sidePanelWidth: 0.25
  border: rounded

  theme:
    # Current line highlight
    selectedLineBgColor:
      - black

    # Default text color
    defaultFgColor:
      - white
      - bold

    # Borders
    activeBorderColor:
      - yellow
    inactiveBorderColor:
      - default
    searchingActiveBorderColor:
      - cyan

    optionsTextColor:
      - blue

    # Commits & branches
    cherryPickedCommitFgColor:
      - yellow
    markedBaseCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
