#!/usr/bin/env bash
if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$( (
    echo "$HOME"
    # 1. --max-depth 4 invece di 5 riduce drasticamente l'albero di ricerca
    # 2. --exclude '.*' esclude le cartelle nascoste di primo livello (sostituisce awk)
    # 3. --exclude per la cache locale
    fd --type d --max-depth 4 \
      --exclude '.*' \
      --exclude '.cache' \
      --exclude 'go' --exclude 'yay' \
      . "$HOME"
  ) | fzf --color='hl:#CBA85E,hl+:#CBA85E' --no-preview --prompt $'⚡Session: ' )
fi

[[ -z "$selected" ]] && exit 0
selected="${selected%/}"
session_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t "$session_name" 2>/dev/null; then
  tmux new-session -d -s "$session_name" -c "$selected"
fi

[[ -n "$TMUX" ]] && tmux switch-client -t "$session_name" || tmux attach -t "$session_name"
