#!/usr/bin/env bash
session=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | \
  fzf --color='hl:#FE8E40,hl+:#FE8E40' --no-preview --ansi --prompt $'\033[32m Find: \033[0m')
[[ -z "$session" ]] && exit 0
[[ -n "$TMUX" ]] && tmux switch-client -t "$session" || tmux attach -t "$session"
