[general]

[terminal]

shell = "zsh"


[window]

padding         = { x = 15, y = 8 }
opacity         = 0.5
# decorations: "None" for borderless, "Full" for native title bar
# decorations = "Full"


[font]
size = 14.0

[font.normal]
family = "JetBrains Mono Nerd"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd"
style = "Thin Bold"

[font.italic]
family = "JetBrains Mono Nerd"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono Nerd"
style = "Bold Italic"
[font.offset]

y = 3 # subtle line spacing

[colors.primary]
background = '#0D0C0C'
foreground = '#C5C9C5'

[colors.normal]
black   = '#0D0C0C'
red     = '#C4746E'
green   = '#8A9A86'
yellow  = '#C4B28A'
blue    = '#8BA4B0'
magenta = '#A292A3'
cyan    = '#8EA4A2'
white   = '#C5C9C5'

[colors.bright]
black   = '#A2A2A2'
red     = '#E46876'
green   = '#87A987'
yellow  = '#E6C384'
blue    = '#7FB4CA'
magenta = '#938AA9'
cyan    = '#7AA89F'
white   = '#E6EAE6'

[colors.selection]
text = '#C5C9C5'
background = '#2D4F67'

[colors.cursor]
text = '#12120F'
cursor = '#C8C093'
